### ISSUE TITLE
Crash with Fabric Seasons: Mixin transformation of net.minecraft.class_3085 failed

### ISSUE THREAD

**Issue by Sarund9** [KdotJPG/Simply-Improved-Terrain#30]
```
Minecraft: 1.20.1
Fabric: 0.15.3
Simply Improved Terrain: ??
Fabric Seasons: 2.3+1.20
```
> java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3085 failed

[Logger Output](https://gist.github.com/Sarund9/d8b5e798a8959a2edc009af2893ab0f1)
There is no crash report because the game failed to initialize

**Comment by KdotJPG** [comment]
Seems related to the [LakeFeature mixin](https://github.com/KdotJPG/Simply-Improved-Terrain/blob/1.20/common/src/main/java/jpg/k/simplyimprovedterrain/mixin/MixinLakeFeature.java) here which is inherently tricky compatibility-wise due to the effective necessity of `@Overwrite`. Looks to be [this mixin](https://github.com/lucaargolo/fabric-seasons/blob/ceca3676f7b322060404864a8f28138141073fbb/src/main/java/io/github/lucaargolo/seasons/mixin/LakeFeatureMixin.java#L23) from Fabric Seasons that it's conflicting with. I believe it's related to all of the local captures in the Fabric Seasons method, which no longer align with the overwritten method in this mod.

Thanks for the report! I'll see what the right solution might be.

**Comment by KdotJPG** [comment]
Reorganized the variables in the mixin and it seems to be working now. Feel free to try version 0.5.4.0-alpha once it shows up on the Curseforge page.
