### ISSUE TITLE
Seems to prevent the promenade dark amaranth forest from appearing. [1.20.1]

### ISSUE THREAD

**Issue by Roadhog360** [KdotJPG/Simply-Improved-Terrain#31]
~~If Sinytra Connector is not a supported mod, then I apologize for the trouble, please close this immediately. I do understand that it's something that not everyone may support due to its very nature.~~ This issue is not related to Sinytra connector after all.

[The mod in question can be found here.](https://modrinth.com/mod/promenade)

As a side note, its overworld biomes appear to function correctly.

Edit: I should probably mention other biome mods I am using. I am using The Outer End which works, but that may be due to it being a Forge mod. If I put both of that and promenade together, their biomes work together, but with your mod installed the promenade dark smarsnth forest end biome does not appear.

Other fabric mods I'm using include cinderscape, traverse, and terrestria. All of these mods seem to work flawlessly with your mod installed, so it is just the Promenade end biome that is having issues.

**Comment by Roadhog360** [comment]
Another amendment suggestion is, perhaps a config for each dimension, simply whether SIT should touch it? E.G. if I have a custom nether or end generator, so for conflicts like this instead of you needing to solve them I can just turn off SIT for the offending dimension, and be done with it. If you have no interest in supporting a connected Fabric mod, I humbly request you do this, as this is the path of absolute least resistance to a solution

**Comment by Roadhog360** [comment]
Another amendment suggestion is, perhaps a config for each dimension, simply whether SIT should touch it? E.G. if I have a custom nether or end generator, so for conflicts like this instead of you needing to solve them I can just turn off SIT for the offending dimension, and be done with it. If you have no interest in supporting a connected Fabric mod, I humbly request you do this, as this is the path of absolute least resistance to a solution.

**Comment by KdotJPG** [comment]
Hmm, this might be related either to the mod's attempts at fixing the global noise distributions across world seeds, or to the mixin that replaces the island shaping source in the End biome sampler. I will look into this in hopefully the next week or two when I have more free dev time.

In the meantime, have you perhaps tested the Fabric/Quilt version of this mod with Promenade? I would be slightly surprised if it actually were Sinytra Connector and not a more general conflict, unless Sinytra affects mixin order somehow. Regardless, if the issue is on this mod's end, then I would indeed like to fix it.

Configs are on the roadmap! The goal in my mind will be to have more granular options than simply disabling the changes outright. For example, you would be able to turn off forced separation of interpolated 3D noise channels (overhangs, terrain shaping within biomes), but leave on forced full-resolution of 2D channels (rivers, shore cliffs, End islands, and terrain height ranges).

**Comment by Roadhog360** [comment]
I appreciate the response. No, I have not. I didn't really bother checking if SIT had a Fabric version to test. I apologize for not doing this; I should always be sure to thoroughly test bug reports.

I will do this in the morning.

**Comment by Roadhog360** [comment]
Apologies for being late. I have tested this issue with Promenade and SIT on its own, in a Fabric instance, and the issue still occurs.

**Comment by Roadhog360** [comment]
I understand you are busy and have changes in the pipeline, but as I like SIT I would like to request a temporary fix jar that just disables the part of the end generation that breaks this mod so I can use it. Would you be okay with providing one?

**Comment by KdotJPG** [comment]
I'll see what I can do tonight. I may need a quick break from other projects anyway. 😅

The error seems to come from this dependency modifying the return value of `getNoiseBiome` https://github.com/TerraformersMC/Biolith/blob/9f09191edc3e9498a67a8de23a1a31ac9d1ebd6d/common/src/main/java/com/terraformersmc/biolith/impl/mixin/MixinTheEndBiomeSource.java#L31 while Simply Improved Terrain creates a new method `getBlockNoiseBiome` to get past its granularity limitations. I'll work on converting this into a set of targeted changes to the existing methods.

**Comment by Roadhog360** [comment]
Thank you very much.

**Comment by KdotJPG** [comment]
Seems to be working! Changes pushed to the 1.20 branch; will finish testing and push the .jar tomorrow.

![2024-06-25_01 13 37](https://github.com/KdotJPG/Simply-Improved-Terrain/assets/8829856/02b9e5c2-e6e3-4a5f-b9c6-f52d32b7da68)

**Comment by Roadhog360** [comment]
Wow! Thank you!

**Comment by KdotJPG** [comment]
A few fixes and force-pushes later, it's uploaded to Curseforge as version 0.5.5.0-alpha. Should show up soon!
