### ISSUE TITLE
Terrain broken and mangled when using with Overworld Two

### ISSUE THREAD

**Issue by jakeismyname** [KdotJPG/Simply-Improved-Terrain#9]
When using Simply Improved Terrain and Overworld Two together, terrain gen becomes extremely noisy
![2021-05-29_12 15 50](https://user-images.githubusercontent.com/79329173/120077344-05274400-c078-11eb-9eb5-6b2b5a604338.png)

**Comment by KdotJPG** [comment]
Thanks for the report! This is a known issue with using OW2 and SIT. It seems to come from some of the parameter changes OW2 makes, that aren't compatible with SIT's mixins.  Unfortunately there is no straightforward way to make the two mods synergize, because they both replace a lot of the same things. OW2 adds a modified version of Vanilla's terrain gen that still uses linear interpolation, while a large goal of SIT is to move away from linear interpolation. To get both mods' changes at the same time would require a fully modified version of one of the two.

Here's the related issue: https://github.com/KdotJPG/Simply-Improved-Terrain/issues/4
